# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'GitHubBySwift' do
pod 'SnapKit', '~> 3.2.0'
pod 'SVProgressHUD'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Moya/RxSwift'
pod 'ObjectMapper'
pod 'MJRefresh'
pod 'SwiftyGif'
pod 'SDCycleScrollView','~> 1.66'
end
